KippensGroup1/Pages/Account.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;

namespace KippensGroup1.Pages
{
    public class AccountModel : PageModel
    {
        public string username { get; set; }
        public string Error { get; set; }

        public IActionResult OnGet()
        {
            if (!CurrentLogged.isLoggedIn())
            {
                return Redirect("Login");
            }
            username = CurrentLogged.getUsername();
            Error = "Select an option below";

            return Page();
        }

        public IActionResult OnPostLogout()
        {
            CurrentLogged.logout();
            return Redirect("Index");
        }

        public IActionResult OnPostDonation()
        {
            username = CurrentLogged.getUsername();
            if (CurrentLogged.getRole() != 2 && CurrentLogged.getRole() != 3)
            {
                Error = "You are not authorized to fill out a donation";
                return Page();
            }
            return Redirect("Donation");
        }

        public IActionResult OnPostTransaction()
        {
            username = CurrentLogged.getUsername();
            if (CurrentLogged.getRole() != 2 && CurrentLogged.getRole() != 3)
            {
                Error = "You are not authorized to fill out a transaction";
                return Page();
            }
            return Redirect("Transactions");
        }

        public IActionResult OnPostReport()
        {
            username = CurrentLogged.getUsername();
            System.Diagnostics.Debug.WriteLine(CurrentLogged.getRole());
            if (CurrentLogged.getRole() != 2 && CurrentLogged.getRole() != 3)
            {
                Error = "You are not authorized to search for reports";
                return Page();
            }
            return Redirect("GetReport");
        }

        public IActionResult OnPostPromote(string user)
        {
            if (CurrentLogged.getRole() == 1)
            {
                Error = "You are not authorized to promote users";
                return Page();
            }
            DBHandler db = new DBHandler(DBHandler.connectionStringBuilder(MysqlLogins.getMySqlUser(), MysqlLogins.getMySqlPass()));
            string query = "SELECT username FROM user WHERE username='" + user + "';";
            MySqlDataReader reader = db.performQuery(query);
            Error = "Unknown error occured";
            if (!reader.HasRows)
            {
                Error = "No user found";
            }
            else
            {
                query = "UPDATE user SET roleID = '" + CurrentLogged.getRole() + "' WHERE username='" + user + "';";
                reader = db.performQuery(query);
                Error = "Update successful";
            }
            
            username= CurrentLogged.getUsername();
            return Page();
        }
    }
}

KippensGroup1/Pages/Cloth.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KippensGroup1.Pages
{
    public class ClothModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

KippensGroup1/Pages/Counseling.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;

namespace KippensGroup1.Pages.Shared
{
    public class CounselingModel : PageModel
    {
        public List<Database_Tables_Classes.Counselers> counselers;
        public void OnGet()
        {
            DBHandler db = new DBHandler(DBHandler.connectionStringBuilder(MysqlLogins.getMySqlUser(), MysqlLogins.getMySqlPass()));
            string query = "SELECT * FROM counselors;";
            MySqlDataReader reader = db.performQuery(query);
            counselers = new List<Database_Tables_Classes.Counselers>();
            while (reader.Read())
            {                
                counselers.Add(new Database_Tables_Classes.Counselers(reader.GetInt32("counselorID"), reader.GetInt32("userID")));
            }
        }
    }
}

KippensGroup1/Pages/Donation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;

namespace KippensGroup1.Pages
{
    public class DonationModel : PageModel
    {
        public string Error { get; set; }

        public void OnGet()
        {
            Error = "Fill out the info below";
        }

        public IActionResult OnPostDonation(string name, string description, string quantity)
        {
            int quantityValue;
            if (!int.TryParse(quantity, out quantityValue)) {
                Error = "Quantity needs to be a number value";
                return Page();
            }
            if (name == null || description == null || quantityValue == null)
            {
                Error = "error, no fields can be left blank";
                return Page();
            }
            else {
                DBHandler db = new DBHandler(DBHandler.connectionStringBuilder(MysqlLogins.getMySqlUser(), MysqlLogins.getMySqlPass()));
                string query = "INSERT INTO donation(name, description, userID, time, roleID, QUANTITY) VALUES ('" + name + "', '" + description + "', '" + CurrentLogged.getID() + "', '" + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") + "', '" + CurrentLogged.getRole() + "', '" + quantityValue + "');";
                MySqlDataReader reader;
               
                try
                {
                reader = db.performQuery(query);
                    if (reader == null)
                    {
                        Error = "can not perform query";
                        return Page();
                    }
                }
                catch(Exception e)
                {
                    Error = "Could not perform query";
                    return Page();
                }
            }


            return Redirect("Account");
        }
    }
}

KippensGroup1/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KippensGroup1.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

KippensGroup1/Pages/Food.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KippensGroup1.Pages
{
    public class FoodModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

KippensGroup1/Pages/GetReport.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KippensGroup1.Database_Tables_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KippensGroup1
{
    public class GetReportModel : PageModel
    {
        [BindProperty]
        public string StartDate { get; set; }

        [BindProperty]
        public string EndDate { get; set; }


        public void OnGet()
        {

            System.Diagnostics.Debug.WriteLine(CurrentLogged.getRole());

        }

        // when user clicks submit button it redirects to ShowReport pages passing startDate and endDate
        public IActionResult OnPostSubmit()
        { 
            return RedirectToPage("ShowReport", "page", new { start = StartDate, end = EndDate });
        }

    }
}

KippensGroup1/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KippensGroup1.Pages
{
    public class IndexModel : PageModel
    {
        public string logged { get; set; }
        public void OnGet()
        {
            logged = CurrentLogged.isLoggedIn().ToString();
        }
    }
}

KippensGroup1/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KippensGroup1.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

KippensGroup1/Pages/ShowReport.cshtml.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using KippensGroup1.Database_Tables_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;

namespace KippensGroup1
{
    public class ShowReportModel : PageModel
    {
        public List<Donation> Donations { get; set; } // List of all records in donation table

        public List<Transaction> Transactions { get; set; } // List of all records in transactions table

        public List<Volunteer> Volunteers { get; set; } // List of all records in volunteer table

        public List<User> Users { get; set; }

        public void OnGet()
        {

        }

        // populates all lists with data from database
        public IActionResult OnGetPage(string start, string end)
        {
            var donAccess = new DatabaseAccess();
            Donations = donAccess.GetDonations(start, end);
            Transactions = donAccess.GetTransactions(start, end);
            Volunteers = donAccess.GetVolunteers();
            Users = donAccess.GetUsers();
            return Page();
        }

    }
}

KippensGroup1/Pages/Signup.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;

namespace KippensGroup1.Pages
{
    public class SignupModel : PageModel
    {
        public string Error { get; set; }
        private string username;
        private string uid;
        private string pwd;

        public void OnGet()
        {
            Error = "Enter user info: ";
            username = "";
        }


        public IActionResult OnPostSignup(string name, string email, string pass, string number)
        {
            
            if (!emailValidation(email))
            {
                return Page();
            }

            createUsername(email);
            getLoginInfo();
            DBHandler db = new DBHandler(DBHandler.connectionStringBuilder(uid, pwd));
            
            string query = "INSERT INTO user(name, username, email, password, roleID) VALUES ('"+name+"', '"+username+"', '"+email+"', '"+pass+"', 1);";
            db.performQuery(query);
            
            query = "CREATE USER '"+username+"'@'localhost' IDENTIFIED BY '"+pass+"'; GRANT SELECT ON kippens TO '"+username+ "'@'localhost'; FLUSH PRIVILEGES;";
            db.performQuery(query);
            

            return Redirect("Index");
        }

        private bool emailValidation(string email)
        {
            Error = "Not valid email";
            if(email == null)
            {
                Error = "Email is null";
                return false;
            }

           bool validEmailCheck = false;
           for(int i = 0; i < email.Length; i++)
           {
                if(email[i] == '@')
                {
                    validEmailCheck = true;
                    Error = "The Valid email";
                }
           }

            if (!validEmailCheck)
            {
                return false;
            }

            string query = "SELECT email FROM user WHERE email='"+email+"';";
            DBHandler db = new DBHandler(DBHandler.connectionStringBuilder(MysqlLogins.getMySqlUser(), MysqlLogins.getMySqlPass()));
            MySqlDataReader reader;
            
            try
            {
                reader = db.performQuery(query);
                if (reader.HasRows)
                {
                    Error = "Username already in use";
                    
                    return false;
                }
            }
            catch (Exception e)
            {
                Error = "could not query DB";
                return false;
            }

            
            Error = "Valid email";
            return true;
        }

        private void createUsername(string email)
        {
            username = "";
            for(int i = 0; i < email.Length; i++)
            {
                if (email[i] != '@')
                {
                    username += email[i];
                }
                else
                {
                    break;
                }
            }
        }

        private void getLoginInfo()
        {
            string filename = "mysqlLogin.txt";
            string[] lines = System.IO.File.ReadAllLines(".\\Data files\\" + filename);
            foreach (string line in lines)
            {
                if (line[0] == 'u')
                {
                    this.uid = line.Remove(0, 4);
                }
                else if (line[0] == 'p')
                {
                    this.pwd = line.Remove(0, 4);
                }
            }
        }
    }
}

KippensGroup1/Pages/Tutors.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;

namespace KippensGroup1.Pages
{
    public class TutorsModel : PageModel
    {
        public List<Database_Tables_Classes.Tutors> tutors;
        public void OnGet()
        {
            DBHandler db = new DBHandler(DBHandler.connectionStringBuilder(MysqlLogins.getMySqlUser(), MysqlLogins.getMySqlPass()));
            string query = "SELECT * FROM tutors;";
            MySqlDataReader reader = db.performQuery(query);
            tutors = new List<Database_Tables_Classes.Tutors>();
            while (reader.Read())
            {
                tutors.Add(new Database_Tables_Classes.Tutors(reader.GetInt32("tutorID"), reader.GetInt32("userID"), reader.GetString("subject")));
            }
        }
    }
}

KippensGroup1/Pages/login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;

namespace KippensGroup1.Pages
{
    public class loginModel : PageModel
    {
        public string Error { get; set; }

        public IActionResult OnGet()
        {
            if (CurrentLogged.isLoggedIn())
            {
                return Redirect("Account");
            }
            Error = "Enter your username and password";
            return null;
        }

        public IActionResult OnPostLogin(string user, string pass)
        {
            string query = "SELECT username, password, userID, roleID FROM user WHERE username='"+user+"' AND password='"+pass+"';";
            DBHandler db = new DBHandler(DBHandler.connectionStringBuilder(MysqlLogins.getMySqlUser(), MysqlLogins.getMySqlPass())); // change to username and password later
            MySqlDataReader reader;
            try
            {
                reader = db.performQuery(query);
                if(reader == null)
                {
                    Error = "Could not Query. reader is null";
                    
                    return Page();
                }
                else if (!reader.HasRows)
                {
                    Error = "Could not Login. Bad username or password";
                    
                    return Page();
                }
                else
                {
                    reader.Read();
                    CurrentLogged.login(reader.GetString("username"), reader.GetInt32("userID"), reader.GetInt32("roleID"));
                    return Redirect("Account");
                }
            }   
            catch (Exception e)
            {
                Error = "Error Querying Database"+db.getError();
                return Page();
            }
            
                               
        }

        public IActionResult OnPostSignup()
        {
            Error = "test";
            return Redirect("Signup");
        }
    }
}

KippensGroup1/Pages/Account.cshtml
@page
@model KippensGroup1.Pages.AccountModel
@{
    ViewData["Title"] = "Account";
}

<html>
<body>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div id="account">
        <h2>Account</h2>
        <br>
        <br>
        <label asp-for="username">@Model.username</label>
        <br>
        <br>
        <label asp-for="Error">@Model.Error</label>
        <br>
        <br>
        <form asp-page-handler="report" method="post">
            <input type="submit" value="Search Reports" />
        </form>
        <br />
        <br />
        <form asp-page-handler="donation" method="post">
            <input type="submit" value="Fill out a donation" />
        </form>
        <br />
        <br />
        <form asp-page-handler="transaction" method="post">
            <input type="submit" value="Fill out a transaction" />
        </form>
        <br />
        <br />
        <form asp-page-handler="promote" method="post">
            <label>Type in username of of user you wish to promote</label><br /><br />
            <input type="text" name="user" /><br /><br />
            <input type="submit" value="Promote user" />
        </form>
        <br />
        <br />
        <form asp-page-handler="logout" method="post">
            <input type="submit" value="Logout" />
        </form>
    </div>
</body>
</html>

KippensGroup1/Pages/Cloth.cshtml
@page
@model KippensGroup1.Pages.ClothModel
@{
    ViewData["Title"] = "Cloth";
}

<html>
<body>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div id="account">
        <h2>Our Clothing closet services many people in our community.</h2>
        <h3>These are the items we have usually in stock. We always accept donations.</h3>
        <ul>
            <li>Men's clothing</li>
            <li>Woman's clothing</li>
            <li>Kids clothes</li>
            <li>Baby/toddler clothes</li>
            <li>Accessories</li>
        </ul>
    </div>
</body>
</html>

KippensGroup1/Pages/Counseling.cshtml
@page
@model KippensGroup1.Pages.Shared.CounselingModel
@{
    ViewData["Title"] = "Counseling";
}

<html>
<head>
    <style>
        h1 {
            align-content: center;
        }

        #tbl {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 70%;
        }

            #tbl td, #customers th {
                border: 1px solid #ddd;
                padding: 8px;
            }

            #tbl tr:nth-child(even) {
                background-color: white;
            }

            #tbl tr:hover {
                background-color: whitesmoke;
            }

            #tbl th {
                padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: rgb(0, 0, 128);
                color: white;
            }
    </style>
</head>

<body>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div id="account">
        <h3> Welcome to our Counseling page. If you wish to find out more information or sign up for counseling, contact one of the counselers below.</h3>

        <table align="center" id="tbl" border="1">
            <thead>
                <tr>
                    <th>Name:</th>
                    <th>Email:</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var coun in Model.counselers)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(Model => coun.name)
                        </td>
                        <td>
                            @Html.DisplayFor(Model => coun.email)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

KippensGroup1/Pages/Donation.cshtml
@page
@model KippensGroup1.Pages.DonationModel
@{
    ViewData["Title"] = "Donation";
}

<html>
<body>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div id="account">
    <h2>Donation</h2>
    <label asp-for="Error">@Model.Error</label>
    <form asp-page-handler="donation" post="method">
        <label>Name: </label>
        <input type="text" name="name" required="required" />
        <br>
        <br>
        <label>Description of Donation: </label>
        <input type="text" name="description" required="required" />
        <br>
        <br>
        <label>Quantity: </label>
        <input type="text" name="quantity" required="required" />
        <br>
        <br>
        <input type="submit" name="submit" value="submit" />
    </form>
</div>
</body>
</html>

KippensGroup1/Pages/Food.cshtml
@page
@model KippensGroup1.Pages.FoodModel
@{
    ViewData["Title"] = "Food";
}


<html>
<body>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div id="account">
        <h2>Our Food Pantry services many people in our community.</h2>
        <h3>These are the items we have usually in stock. We always accept donations.</h3>
        <ul>
            <li>Canned food</li>
            <li>Sauces</li>
            <li>Pastas</li>
            <li>Condements</li>
            <li>And many others</li>
        </ul>
    </div>
</body>
</html>

KippensGroup1/Pages/GetReport.cshtml
@page
@model KippensGroup1.GetReportModel
@{
    ViewData["Title"] = "GetReport";

}

<html>
<body>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div id="account">
        <br />
        <form asp-page-handler="submit" method="post">
            <br />
            <br />
            <label for="date">&nbsp;&nbsp; start of report:</label>
            <input type="date" name="startDate">
            <label for="date">&nbsp; end of report:</label>
            <input type="date" name="endDate">
            <input type="submit" name="submit">
        </form>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br />
</body>

</html>

KippensGroup1/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<html>

<body>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div id="account">
        <h1> Welcome to Kippens Corner!</h1>
        <p> We offer a variety of services such as Counseling and Tutoring services for kids along with a food pantry and clothing closet! </p>
        <p> If you wish to get updates or volenteer or have any questions, create an account and contact us! </p>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</body>
</html>

KippensGroup1/Pages/ShowReport.cshtml
@page
@model KippensGroup1.ShowReportModel
@{
    ViewData["Title"] = "ShowReport";

}

<html>
<head>
    <style>
        h1 {
            align-content:center;
        }
        #tbl {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 70%;
        }

            #tbl td, #customers th {
                border: 1px solid #ddd;
                padding: 8px;
            }

            #tbl tr:nth-child(even) {
                background-color: white;
            }

            #tbl tr:hover {
                background-color: whitesmoke;
            }

            #tbl th {
                padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: rgb(0, 0, 128);
                color: white;
            }
    </style>
</head>
<body>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br />
    <h1 style="text-align:center">Donations Report</h1>
    <table align="center" id="tbl" border="1">
        <tr>
            <th width="100px">Name</th>
            <th width="100px">Description</th>
            <th width="100px">UserID</th>
            <th width="100px">DonationID</th>
            <th width="100px">Date Donated</th>
            <th width="100px">RoleID</th>
            <th width="100px">Quantity</th>
        </tr>

        @{
            for (int i = 0; i < Model.Donations.Count; i++)
            {
                <tr>
                    <td>@Model.Donations.ElementAt(i).Name</td>

                    <td>@Model.Donations.ElementAt(i).description</td>

                    <td>@Model.Donations.ElementAt(i).userID</td>

                    <td>@Model.Donations.ElementAt(i).donationID</td>

                    <td>@Model.Donations.ElementAt(i).time</td>

                    <td>@Model.Donations.ElementAt(i).roleID</td>

                    <td>@Model.Donations.ElementAt(i).QUANTITY</td>
                </tr>
            }
        }
    </table>
    <br />
    <br />
    <br />
    <h1 style="text-align:center">Transactions Report</h1>
    <table id="tbl" align="center" border="1">
        <tr>
            <th width="100px">TransactionID</th>
            <th width="100px">Date</th>
            <th width="100px">RoleID</th>
            <th width="100px">Name</th>
            <th width="100px">Description</th>
            <th width="100px">UserID</th>
            <th width="100px">Quantity</th>
        </tr>

        @{
            for (int i = 0; i < Model.Transactions.Count; i++)
            {
                <tr>
                    <td>@Model.Transactions.ElementAt(i).transactionID</td>

                    <td>@Model.Transactions.ElementAt(i).time</td>

                    <td>@Model.Transactions.ElementAt(i).roleID</td>

                    <td>@Model.Transactions.ElementAt(i).name</td>

                    <td>@Model.Transactions.ElementAt(i).description</td>

                    <td>@Model.Transactions.ElementAt(i).userID</td>

                    <td>@Model.Transactions.ElementAt(i).QUANTITY</td>
                </tr>
            }
        }
    </table>
    <br />
    <br />
    <br />
    <h1 style="text-align:center">Volunteer Report</h1>
    <table id="tbl" align="center" border="1">
        <tr>
            <th width="100px">VolunteerID</th>
            <th width="100px">userID</th>
            <th width="100px">Name</th>
            <th width="100px">Role</th>
        </tr>

        @{
            for (int i = 0; i < Model.Volunteers.Count; i++)
            {
                <tr>
                    <td>@Model.Volunteers.ElementAt(i).volunteerID</td>

                    <td>@Model.Volunteers.ElementAt(i).userID</td>

                    <td>@Model.Volunteers.ElementAt(i).name</td>

                    <td>@Model.Volunteers.ElementAt(i).role</td>
                </tr>
            }
        }
    </table>
    <br />
    <br />
    <br />
</body>
</html>

KippensGroup1/Pages/Signup.cshtml
@page
@model KippensGroup1.Pages.SignupModel
@{
    ViewData["Title"] = "Signup";
}


<html>
<body>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <label asp-for="Error">@Model.Error</label>
    <h2>Signup</h2>
    <form asp-page-handler="signup" method="post">
        <label>Name: </label>
        <input name="name" type="text" required="required">
        <br>
        <br>
        <label>Email: </label>
        <input name="email" type="email" required="required">
        <br>
        <br>
        <label>Password: </label>
        <input name="pass" type="password" required="required">
        <br>
        <br>
        <label>Number(optional): </label>
        <input name="name" type="text">
        <br>
        <br>
        <input name="submit" type="submit">
    </form>

</body>
</html>

KippensGroup1/Pages/Transactions.cshtml
@page
@model KippensGroup1.Pages.TransactionsModel
@{
    ViewData["Title"] = "Transactions";
}

<html>
<body>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div id="account">
    <h2>Transaction</h2>
    <label asp-for="Error">@Model.Error</label>
    <form asp-page-handler="donation" post="method">
        <label>Name: </label>
        <input type="text" name="name" required="required" />
        <br>
        <br>
        <label>Description of Transaction: </label>
        <input type="text" name="description" required="required" />
        <br>
        <br>
        <label>Quantity: </label>
        <input type="text" name="quantity" required="required" />
        <br>
        <br>
        <input type="submit" name="submit" value="submit" />
    </form>
</div>
</body>
</html>

KippensGroup1/Pages/login.cshtml
@page
@model KippensGroup1.Pages.loginModel
@{
    ViewData["Title"] = "login";
}

<html>
<body>


    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div id="account">
        <h2> Login: </h2>
        <label asp-for="Error">@Model.Error</label>
        <br>
        <br />

        <form asp-page-handler="login" method="post">
            <label> Username:</label>
            <input name="user" type="text" required="required">
            <br>
            <br>
            <label> Password:</label>
            <input name="pass" type="password" required="required">
            <br />
            <br />
            <input type="submit" name="login" value="Submit">
        </form>

        <br />
        <form asp-page-handler="signup" method="post">
            <input type="submit" name="signedup" value="Sign up" />
        </form>
    </div>
</body>
</html>